Question 1 Done
MichaelAgonsi/CP1890_OOPS pull request #2
Opened 2024-02-12 14:38 UTC by MichaelAgonsi

I am done with Question 1. Please review, comment and approve to the Assignment Main Branch for later final review.

2024-02-12 14:57 UTC, ZCZDinn requested changes
just minor formatting stuff

2024-02-12 14:57 UTC, ZCZDinn commented on PyThinkers Assignment/Question 1.py
> +    print()
remove newline placement here

2024-02-12 14:57 UTC, ZCZDinn commented on PyThinkers Assignment/Question 1.py
> +        cont = input('Continue ? (y/n): ').lower()
'\nContinue? (y/n): '    for formatting

2024-02-12 14:57 UTC, ZCZDinn commented on PyThinkers Assignment/Question 1.py
> +                height = int(input(f"{'Height:':15} "))
Newline placement works better here for looping   i.e.('\nHeight")

2024-02-12 14:58 UTC, MichaelAgonsi reviewed
Thanks for this

2024-02-12 14:59 UTC, MichaelAgonsi commented on PyThinkers Assignment/Question 1.py
> +                height = int(input(f"{'Height:':15} "))
Nice thanks!

2024-02-12 15:07 UTC, ZCZDinn approved these changes
Great work!!!!

2024-02-17 16:27 UTC, ZCZDinn commented
Question 2 done and documented. It automatically added to the Pull Request from 5 days ago.   **: )**

2024-02-18 23:32 UTC, AseelElzamel approved these changes

2024-02-18 23:33 UTC, merged